<?php
// Your database connection code goes here
require '../../config/includes.php';
require '_session.php';
require '_restriction.php';

$scholarCode = $_GET['scholarCode'];


$studentName = "Juan";
$gradeLevel = "Year";
$schoolYear = "2023-2024";
$course = "Bachelor of Science and Information System";

$subjects = [
    ["Sample", "Sample desc", 2, 90],
    ["Sample", "Sample desc", 2, 90],
    ["Sample", "Sample desc", 2, 90],
];

// Generate PDF using FPDF library
require('fpdf/fpdf.php');

class PDF extends FPDF
{
    function Header()
    {
        // Add header if needed
    }

    function Footer()
    {
        // Add footer if needed
    }
}

$pdf = new PDF();
$pdf->AddPage();
$pdf->SetFont('Arial', 'B', 16);

// Add your HTML template with dynamic data using PHP echo
$html = '
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Document</title>
    <!-- Add your other styles and scripts here -->
</head>

<body style="font-size: 50%">
    <!-- Add your HTML template here -->
    <div class="container-xxl flex-grow-1 container-p-y">
        <!-- ... (rest of your HTML template) ... -->
        <p class="col-4 mb-0">
            <span style="font-weight: bold">Name: </span> ' . $studentName . '
        </p>
        <p class="col-4 mb-0">
            <span style="font-weight: bold">Grade Level: </span> ' . $gradeLevel . '
        </p>
        <p class="col-4 mb-2">
            <span style="font-weight: bold">School Year: </span> ' . $schoolYear . '
        </p>
        <p class="col-7 mb-0">
            <span style="font-weight: bold">Course: </span>' . $course . '
        </p>
        <!-- ... (rest of your HTML template) ... -->

        <tbody class="table-group-divider">';
// Add subject data dynamically
foreach ($subjects as $subject) {
    $html .= '
        <tr>
            <th>' . $subject[0] . '</th>
            <th>' . $subject[1] . '</th>
            <th>' . $subject[2] . '</th>
            <th>' . $subject[3] . '</th>
        </tr>';
}
$html .= '
        </tbody>
        <tfoot class="table-group-divider">
            <td colspan="3" style="font-weight: bold; text-align: right;">GWA</td>
            <td>90</td>
        </tfoot>
    </table>

    <div class="col-12">
        <p style="text-align: right; font-style: italic;">* Grades presented are not from the official school. Generated by the PROWESS System.</p>
    </div>
</div>
</body>
</html>';

$pdf->writeHTML($html);

// Output the PDF as a blob
$pdfContent = $pdf->Output('report.pdf', 'S');

// Set headers for PDF download
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="report.pdf"');
header('Content-Length: ' . strlen($pdfContent));

// Output the PDF content
echo $pdfContent;

?>