<?php
    require '../../config/includes.php';
    require '_session.php';
    include "_head.php";

    $getProfile=selectAllScholarbyHEI(1);
?>
  <style>
    @media print {
      /* Set the page size to A4 */
      @page {
        size: A4;
        margin-left: 1.5cm;
        margin-right: 1.5cm;
        margin-top: 0.2cm;
        margin-bottom: 0.2cm;
      }
    }

    .textcust2{
      font-size:8px!important;
    }
  </style>
  <body class="reportCard">
    <div class="container-xxl flex-grow-1 container-p-y">
      <h3 class="col-12 mb-0 text-center text-primary" style="text-transform: uppercase">Scholar Master List</h3>
      <div class="">
        <div class="col-12 mb-3 text-center">
          <h4 class="col mb-0">School Year: </h4>
          <h6 class="col mb-0">Semester: </h6>
          <hr class="my-2 mx-n2" />
        </div>
      </div>

      <div class="row mb-3">
        
  

      <table class="tables text-custom textcust2">
        <tr>
          <th style="width: 10%;">Scholar Code</th>
          <th style="width: 25%;">Fullname</th>
          <th style="width: 10%;">School ID</th>
          <th style="width: 20%;">School Name</th>
          <th style="width: 35%;">Course</th>
        </tr>
        <tbody>
            <?php 
                while ($pending=$getProfile->fetch(PDO::FETCH_ASSOC)) {
            ?>
            <tr>
                <td><?= $pending['prow_scholar_code'] ?></td>
                <td><?= getFullname($pending['prow_scholar_code'])  ?></td>
                <td><?= getgetScholarSchoolId($pending['prow_scholar_code'])?></td>
                <td><?= getScholarSchool($pending['prow_scholar_code'])  ?></td>
                <td><?= getScholarCourse($pending['prow_scholar_code'])  ?></td>
            </tr>
            <?php } ?>
        </tbody>
          
      </table>

      <div class="col-12 text-custom">
        <p class="mb-0" style="text-align: left; font-style: italic;">* Generated by the PROWESS System - <?= date("Y-m-d H:i:s")?></p>
      </div>
    </div>
   
    <script>
      document.addEventListener('DOMContentLoaded', function () {
        window.print();
      });
    </script>
    
  </body>
</html>
