<?php
    require '../../config/includes.php';
    require '_session.php';

    $scholarCode = clean_string($_GET['scholarCode']);
    
    $getProfile=selectScholar($scholarCode);
    $profile=$getProfile->fetch(PDO::FETCH_ASSOC);
  
    $getGrades=selectScholarGrades($scholarCode);
    $countRes=$getGrades->rowCount();

    include "_head.php";

?>
  <style>
    @media print {
      /* Set the page size to A4 */
      @page {
        size: A4;
        margin-left: 1.5cm;
        margin-right: 1.5cm;
        margin-top: 0.2cm;
        margin-bottom: 0.2cm;
      }
    }
  </style>
  <body class="reportCard">
    <div class="container-xxl flex-grow-1 container-p-y">
      <h3 class="col-12 mb-0 text-center text-primary" style="text-transform: uppercase">Scholar Report Card</h3>
      <div class="">
        <div class="col-12 mb-3 text-center">
          <h4 class="col mb-0"><?= getSchoolScholar($scholarCode) ?></h4>
          <hr class="my-2 mx-n2" />
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-3">
          <center>
          <img
            src="../../imagebankProfiles/<?= $profile['prow_scholar_img'] ?>"
            alt="School Logo"
            class="scholarID"
          />
          </center>
        </div>
        <div class="col-9">
          <div class="card-body">
            <ul class="list-unstyled mb-0 pt-1">
              <li class="d-flex align-items-center mb-1">
                <i class="mdi mdi-account-outline mdi-20px"></i
                ><span class="fw-semibold mx-2">Student Name:</span> <span><?= getFullname($scholarCode) ?></span>
              </li>
              <li class="d-flex align-items-center mb-1">
                <i class="mdi mdi-book-check-outline mdi-20px"></i
                ><span class="fw-semibold mx-2">Course:</span> <span><?= getScholarCourse($scholarCode)  ?></span>
              </li>
              <li class="d-flex align-items-center mb-1">
                <i class="mdi mdi-badge-account-outline mdi-20px"></i><span class="fw-semibold mx-2">School ID:</span>
                <span><?= $profile['prow_scholar_school_id'] ?></span>
              </li>
              <li class="d-flex align-items-center">
                <i class="mdi mdi-book-open-outline mdi-20px"></i
                ><span class="fw-semibold mx-2">Year Level:</span> <span><?= getScholarYrLvl($scholarCode)?></span>
              </li>
            </ul>
          </div>
        </div>      </div>

      

      <table class="tables text-custom">
        <tr>
          <th class="text-center" style="text-transform: uppercase">School Year</th>
          <th class="text-center" style="text-transform: uppercase">Sem</th>
          <th class="text-center" style="text-transform: uppercase">Subject Code</th>
          <th class="text-center" style="text-transform: uppercase">Subject Description</th>
          <th class="text-center" style="text-transform: uppercase">Units</th>
          <th class="text-center text-primary" style="text-transform: uppercase">Grade</th>
        </tr>
        <tbody>
            <?php 
                while ($grade=$getGrades->fetch(PDO::FETCH_ASSOC)) {
            ?>
            <tr>
                <td class="text-center" ><?= $grade['prow_scholar_grades_sy'] ?></td>
                <td><?= getSubjectSemester($grade['prow_subject_id'],$scholarCode) ?></td>
                <td><?= getSubjectCode($grade['prow_subject_id']) ?></td>
                <td><?= getSubjectDesc($grade['prow_subject_id']) ?></td>
                <td class="text-center"><?= getSubjectUnits($grade['prow_subject_id']) ?></td>
                <td class="text-center text-primary"><?= $grade['prow_scholar_grades_percent'] ?></td>
            </tr>
            <?php } ?>
        </tbody>
          <td colspan="5" style="font-weight: bold; text-align: right;">GWA</td>
          <td class="text-center text-primary">90</td>

      </table>

      <div class="col-12 text-custom">
        <p class="mb-0 " style="text-align: left; font-style: italic;">* Grades presented are not from the official school.</p>
        <p class="mb-0" style="text-align: left; font-style: italic;">* Generated by the PROWESS System - <?= date("Y-m-d H:i:s")?></p>
      </div>
    </div>
   
    <script>
      document.addEventListener('DOMContentLoaded', function () {
        window.print();
      });
    </script>
    
  </body>
</html>
